server:
  port: 8011
#  servlet:
#    context-path: user-base-server

spring:
  security:
    user:
      name: 11
      password: 11
  profiles:
    active: dev
  application:
    name: ${user.base-pre}user-base
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    tomcat:
      max-active: 20
      max-idle: 8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
          content-type: text/html
    #热部署文件，页面不产生缓存，及时更新
    cache: false
  #redis setting
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
  #rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
        simple:
          concurrency: 10
          max-concurrency: 10
          prefetch: 1
          auto-startup: true
          default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1.0

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.user.base.entity.model

#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
# 快速失败配置
feign:
  hystrix:
    enabled: true

#自定义配置
mail:
  smtp:
    auth: true
    host: smtp.qq.com
    port: 587
  user: 920555576@qq.com
  password: dnzjruwrozcmbbdf
#服务器前缀
user.base-pre: 14








 
  

