server:
  port: 8011

spring:
  security:
    user:
      name: 11
      password: 11
  profiles:
    active: dev
  application:
    name: user-base
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    tomcat:
      max-active: 20
      max-idle: 8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
          content-type: text/html
    #热部署文件，页面不产生缓存，及时更新
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.user.base.entity.model

#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

#自定义注解






 
  

