server:
  port: 8011

#该应用是否启用生产者
rocketmq:
  producer:
    isOnOff: on
    #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: ${spring.application.name}
#mq的nameserver地址
    namesrvAddr: 127.0.0.1:9876
#消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
#发送消息超时时间,默认3000
    sendMsgTimeout: 3000
#发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2

##该应用是否启用消费者
rocketmq:
  consumer:
    isOnOff: on
    groupName: ${spring.application.name}
    #mq的nameserver地址
    namesrvAddr: 127.0.0.1:9876
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    #rocketmq.consumer.topics=DemoTopic~*;
    topics: DemoTopic;
    consumeThreadMin: 20
    consumeThreadMax: 64
    #设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1

spring:
  security:
    user:
      name: 11
      password: 11
  profiles:
    active: dev
  application:
    name: user-base
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.187.129:3306/zeng?useUnicode=true&useSSL=false&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    tomcat:
      max-active: 20
      max-idle: 8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
          content-type: text/html
    #热部署文件，页面不产生缓存，及时更新
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.user.base.entity.model

#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

#自定义注解






 
  

