server:
  port: 8012
spring:
  security:
    user:
      name: 11  
      password: 11
  profiles:
    active: dev
  application:
    name: user-account
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.187.129:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    tomcat:
      max-active: 20
      max-idle: 8
  #rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
        simple:
          concurrency: 10
          max-concurrency: 10
          prefetch: 1
          auto-startup: true
          default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1.0
      
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.user.account.entity.model

#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          strategy: SEMAPHORE



 
  

